import "./globals.css";
import { Inter } from 'next/font/google';
export const metadata = {
    title: 'Next.js 学习',
    description: 'Generated by Next.js',
}
const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
})
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={inter.className}>
            <body>
                {children}
            </body>
        </html>
    )
}
